import { Language, TranslationKeys, ZodiacSign } from './types';

export const ZODIAC_SIGNS: ZodiacSign[] = [
  { name: 'Aries', symbol: '♈', dates: 'Mar 21 - Apr 19', element: 'Fire', icon: 'ram' },
  { name: 'Taurus', symbol: '♉', dates: 'Apr 20 - May 20', element: 'Earth', icon: 'bull' },
  { name: 'Gemini', symbol: '♊', dates: 'May 21 - Jun 20', element: 'Air', icon: 'twins' },
  { name: 'Cancer', symbol: '♋', dates: 'Jun 21 - Jul 22', element: 'Water', icon: 'crab' },
  { name: 'Leo', symbol: '♌', dates: 'Jul 23 - Aug 22', element: 'Fire', icon: 'lion' },
  { name: 'Virgo', symbol: '♍', dates: 'Aug 23 - Sep 22', element: 'Earth', icon: 'virgin' },
  { name: 'Libra', symbol: '♎', dates: 'Sep 23 - Oct 22', element: 'Air', icon: 'scales' },
  { name: 'Scorpio', symbol: '♏', dates: 'Oct 23 - Nov 21', element: 'Water', icon: 'scorpion' },
  { name: 'Sagittarius', symbol: '♐', dates: 'Nov 22 - Dec 21', element: 'Fire', icon: 'archer' },
  { name: 'Capricorn', symbol: '♑', dates: 'Dec 22 - Jan 19', element: 'Earth', icon: 'goat' },
  { name: 'Aquarius', symbol: '♒', dates: 'Jan 20 - Feb 18', element: 'Air', icon: 'bearer' },
  { name: 'Pisces', symbol: '♓', dates: 'Feb 19 - Mar 20', element: 'Water', icon: 'fish' },
];

export const TRANSLATIONS: Record<Language, TranslationKeys> = {
  [Language.ENGLISH]: {
    welcome: "Welcome to Astro Ved AI",
    selectLanguage: "Select Your Language",
    continue: "Continue",
    home: "Home",
    horoscope: "Horoscope",
    kundli: "Kundli",
    compatibility: "Match",
    chat: "Ask AI",
    settings: "Settings",
    findRashi: "Find My Rashi",
    dailyInsight: "Cosmic Insight",
    luckyColor: "Lucky Color",
    luckyNumber: "Lucky Number",
    mood: "Mood Meter",
    askAstro: "Ask Astro AI",
    birthDetails: "Birth Details",
    name: "Name",
    dob: "Date of Birth",
    tob: "Time of Birth",
    pob: "Place of Birth",
    generate: "Generate Insight",
    partner: "Partner Details",
    analyze: "Analyze Match",
    chatPlaceholder: "Ask about your destiny...",
    loading: "Consulting the Stars...",
    loadingSubtitle: "Preparing your reading... the universe is aligning your details",
    zodiac: { aries: "Aries", taurus: "Taurus", gemini: "Gemini", cancer: "Cancer", leo: "Leo", virgo: "Virgo", libra: "Libra", scorpio: "Scorpio", sagittarius: "Sagittarius", capricorn: "Capricorn", aquarius: "Aquarius", pisces: "Pisces" },
    settingsTitle: "App Settings",
    notifications: "Notifications",
    enableAlerts: "Daily Horoscope Alerts",
    selectSign: "Select Your Sign",
    saveChanges: "Save Changes",
    viewDetails: "View Details",
    timeframes: { today: "Today", tomorrow: "Tomorrow", weekly: "Weekly" },
    features: { zodiacSigns: "Zodiac Signs", kundliDesc: "Vedic Chart", matchDesc: "Love Match" },
    profile: "Profile",
    bio: "Bio",
    editProfile: "Edit Profile",
    cancel: "Cancel",
    matchTitle: "Match Compatibility",
    matchSubtitle: "Find how well you both align",
    yourDetails: "Your Details",
    partnerDetails: "Partner Details",
    gender: "Gender",
    male: "Male",
    female: "Female",
    other: "Other",
    relType: "Relationship Type",
    relTypes: { love: "Love", marriage: "Marriage", friendship: "Friendship", general: "General" },
    checkMatch: "Check Compatibility",
    matchScore: "Match Score",
    strengths: "Strengths",
    challenges: "Challenges",
    advice: "Cosmic Advice",
    emotional: "Emotional",
    communication: "Communication",
    longTerm: "Long-term Outlook",
    share: "Share Result",
    privacyPolicy: "Privacy Policy",
    login: "Login",
    signup: "Sign Up",
    email: "Email",
    password: "Password",
    forgotPassword: "Forgot Password?",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    continueWithGoogle: "Continue with Google",
    logout: "Logout",
    welcomeBack: "Welcome Back",
    createAccount: "Create Account",
    numerology: "Numerology",
    comingSoon: "Coming Soon"
  },
  [Language.HINDI]: {
    welcome: "एस्ट्रो वेद एआई में आपका स्वागत है",
    selectLanguage: "अपनी भाषा चुनें",
    continue: "जारी रखें",
    home: "होम",
    horoscope: "राशिफल",
    kundli: "कुंडली",
    compatibility: "मिलान",
    chat: "चैट",
    settings: "सेटिंग्स",
    findRashi: "राशि खोजें",
    dailyInsight: "दैनिक संकेत",
    luckyColor: "शुभ रंग",
    luckyNumber: "शुभ अंक",
    mood: "मनोदशा",
    askAstro: "एस्ट्रो एआई",
    birthDetails: "जन्म विवरण",
    name: "नाम",
    dob: "जन्म तिथि",
    tob: "जन्म समय",
    pob: "जन्म स्थान",
    generate: "कुंडली बनाएं",
    partner: "साथी का विवरण",
    analyze: "गुण मिलान",
    chatPlaceholder: "अपने भाग्य के बारे में पूछें...",
    loading: "सितारों से परामर्श...",
    loadingSubtitle: "कुंडली तैयार हो रही है... ब्रह्मांड आपके लिए उत्तर जुटा रहा है",
    zodiac: { aries: "मेष", taurus: "वृषभ", gemini: "मिथुन", cancer: "कर्क", leo: "सिंह", virgo: "कन्या", libra: "तुला", scorpio: "वृश्चिक", sagittarius: "धनु", capricorn: "मकर", aquarius: "कुंभ", pisces: "मीन" },
    settingsTitle: "सेटिंग्स",
    notifications: "सूचनाएं",
    enableAlerts: "दैनिक राशिफल अलर्ट",
    selectSign: "अपनी राशि चुनें",
    saveChanges: "बदलाव सहेजें",
    viewDetails: "विवरण देखें",
    timeframes: { today: "आज", tomorrow: "कल", weekly: "साप्ताहिक" },
    features: { zodiacSigns: "राशि चिन्ह", kundliDesc: "वैदिक चार्ट", matchDesc: "प्रेम मिलान" },
    profile: "प्रोफाइल",
    bio: "परिचय",
    editProfile: "प्रोफाइल संपादित करें",
    cancel: "रद्द करें",
    matchTitle: "राशि मिलान",
    matchSubtitle: "जानें कि आप दोनों कितने अनुकूल हैं",
    yourDetails: "आपका विवरण",
    partnerDetails: "साथी का विवरण",
    gender: "लिंग",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    relType: "संबंध का प्रकार",
    relTypes: { love: "प्रेम", marriage: "विवाह", friendship: "मित्रता", general: "सामान्य" },
    checkMatch: "मिलान जांचें",
    matchScore: "मिलान स्कोर",
    strengths: "मजबूत पक्ष",
    challenges: "चुनौतियां",
    advice: "ब्रह्मांडीय सलाह",
    emotional: "भावनात्मक",
    communication: "संचार",
    longTerm: "दीर्घकालिक दृष्टिकोण",
    share: "परिणाम साझा करें",
    privacyPolicy: "गोपनीयता नीति",
    login: "लॉग इन",
    signup: "साइन अप",
    email: "ईमेल",
    password: "पासवर्ड",
    forgotPassword: "पासवर्ड भूल गए?",
    dontHaveAccount: "खाता नहीं है?",
    alreadyHaveAccount: "पहले से खाता है?",
    continueWithGoogle: "Google के साथ जारी रखें",
    logout: "लॉग आउट",
    welcomeBack: "वापसी पर स्वागत है",
    createAccount: "खाता बनाएं",
    numerology: "अंक ज्योतिष",
    comingSoon: "जल्द आ रहा है"
  },
  [Language.MARATHI]: {
    welcome: "अ‍ॅस्ट्रो वेद एआय मध्ये स्वागत आहे",
    selectLanguage: "भाषा निवडा",
    continue: "पुढे जा",
    home: "होम",
    horoscope: "राशीभविष्य",
    kundli: "कुंडली",
    compatibility: "गुणमेलन",
    chat: "चॅट",
    settings: "सेटिंग्ज",
    findRashi: "राशी शोधा",
    dailyInsight: "दैनिक अंतर्दृष्टी",
    luckyColor: "शुभ रंग",
    luckyNumber: "शुभ अंक",
    mood: "मनस्थिती",
    askAstro: "अ‍ॅस्ट्रो एआय",
    birthDetails: "जन्म तपशील",
    name: "नाव",
    dob: "जन्म तारीख",
    tob: "जन्म वेळ",
    pob: "जन्म ठिकाण",
    generate: "माहिती मिळवा",
    partner: "जोडीदाराचे तपशील",
    analyze: "गुणमेलन करा",
    chatPlaceholder: "भविष्याबद्दल विचारा...",
    loading: "ताऱ्यांशी संपर्क साधत आहे...",
    loadingSubtitle: "आपली कुंडली तयार होत आहे... ब्रह्मांड तपशील जुळवत आहे",
    zodiac: { aries: "मेष", taurus: "वृषभ", gemini: "मिथुन", cancer: "कर्क", leo: "सिंह", virgo: "कन्या", libra: "तुला", scorpio: "वृश्चिक", sagittarius: "धनु", capricorn: "मकर", aquarius: "कुंभ", pisces: "मीन" },
    settingsTitle: "सेटिंग्ज",
    notifications: "सूचना",
    enableAlerts: "दैनिक राशीभविष्य",
    selectSign: "राशी निवडा",
    saveChanges: "जतन करा",
    viewDetails: "तपशील पहा",
    timeframes: { today: "आज", tomorrow: "उद्या", weekly: "साप्ताहिक" },
    features: { zodiacSigns: "राशी", kundliDesc: "वैदिक चार्ट", matchDesc: "प्रेम जुळवणी" },
    profile: "प्रोफाइल",
    bio: "परिचय",
    editProfile: "प्रोफाइल संपादित करा",
    cancel: "रद्द करा",
    matchTitle: "गुणमेलन",
    matchSubtitle: "तुमच्या दोघांची जुळवणी तपासा",
    yourDetails: "तुमची माहिती",
    partnerDetails: "जोडीदाराची माहिती",
    gender: "लिंग",
    male: "पुरुष",
    female: "स्त्री",
    other: "इतर",
    relType: "नात्याचा प्रकार",
    relTypes: { love: "प्रेम", marriage: "विवाह", friendship: "मैत्री", general: "सामान्य" },
    checkMatch: "जुळवणी तपासा",
    matchScore: "जुळवणी गुण",
    strengths: "मजबूत बाजू",
    challenges: "आव्हाने",
    advice: "सल्ला",
    emotional: "भावनिक",
    communication: "संवाद",
    longTerm: "दीर्घकालीन",
    share: "शेअर करा",
    privacyPolicy: "गोपनीयता धोरण",
    login: "लॉगिन",
    signup: "साइन अप",
    email: "ईमेल",
    password: "पासवर्ड",
    forgotPassword: "पासवर्ड विसरलात?",
    dontHaveAccount: "खाते नाही?",
    alreadyHaveAccount: "आधीच खाते आहे?",
    continueWithGoogle: "Google सह सुरू ठेवा",
    logout: "लॉग आउट",
    welcomeBack: "पुन्हा स्वागत आहे",
    createAccount: "नवीन खाते तयार करा",
    numerology: "अंकशास्त्र",
    comingSoon: "लवकरच येत आहे"
  },
  [Language.TAMIL]: {
    welcome: "ஆஸ்ட்ரோ வேதா ஏஐ",
    selectLanguage: "மொழியைத் தேர்ந்தெடுக்கவும்",
    continue: "தொடரவும்",
    home: "முகப்பு",
    horoscope: "ராசிபலன்",
    kundli: "ஜாதகம்",
    compatibility: "பொருத்தம்",
    chat: "ஏஐ அரட்டை",
    settings: "அமைப்புகள்",
    findRashi: "என் ராசி",
    dailyInsight: "தினசரி பலன்",
    luckyColor: "அதிர்ஷ்ட நிறம்",
    luckyNumber: "அதிர்ஷ்ட எண்",
    mood: "மனநிலை",
    askAstro: "ஆஸ்ட்ரோ ஏஐ",
    birthDetails: "பிறப்பு விவரங்கள்",
    name: "பெயர்",
    dob: "பிறந்த தேதி",
    tob: "பிறந்த நேரம்",
    pob: "பிறந்த இடம்",
    generate: "கணிக்கவும்",
    partner: "துணைவர் விவரங்கள்",
    analyze: "பகுப்பாய்வு",
    chatPlaceholder: "விதியை பற்றி கேளுங்கள்...",
    loading: "நட்சத்திரங்களை ஆராய்கிறது...",
    loadingSubtitle: "உங்கள் ஜாதகம் தயாராகிறது... பிரபஞ்சம் பதிலளிக்கிறது",
    zodiac: { aries: "மேஷம்", taurus: "ரிஷபம்", gemini: "மிதுனம்", cancer: "கடகம்", leo: "சிம்மம்", virgo: "கன்னி", libra: "துலாம்", scorpio: "விருச்சிகம்", sagittarius: "தனுசு", capricorn: "மகரம்", aquarius: "கும்பம்", pisces: "மீனம்" },
    settingsTitle: "அமைப்புகள்",
    notifications: "அறிவிப்புகள்",
    enableAlerts: "தினசரி ராசிபலன்",
    selectSign: "உங்கள் ராசி",
    saveChanges: "சேமிக்கவும்",
    viewDetails: "விவரங்கள்",
    timeframes: { today: "இன்று", tomorrow: "நாளை", weekly: "வாராந்திர" },
    features: { zodiacSigns: "ராசி அறிகுறிகள்", kundliDesc: "வேத ஜாதகம்", matchDesc: "திருமண பொருத்தம்" },
    profile: "சுயவிவரம்",
    bio: "விவரம்",
    editProfile: "சுயவிவரத்தைத் திருத்து",
    cancel: "ரத்துசெய்",
    matchTitle: "பொருத்தம் பார்த்தல்",
    matchSubtitle: "நீங்கள் இருவரும் எவ்வளவு பொருந்துகிறீர்கள்",
    yourDetails: "உங்கள் விவரங்கள்",
    partnerDetails: "துணைவர் விவரங்கள்",
    gender: "பாலினம்",
    male: "ஆண்",
    female: "பெண்",
    other: "மற்றவை",
    relType: "உறவு வகை",
    relTypes: { love: "காதல்", marriage: "திருமணம்", friendship: "நட்பு", general: "பொது" },
    checkMatch: "பொருத்தம் பார்க்கவும்",
    matchScore: "மதிப்பெண்",
    strengths: "பலங்கள்",
    challenges: "சவால்கள்",
    advice: "அறிவுரை",
    emotional: "உணர்ச்சி",
    communication: "தொடர்பு",
    longTerm: "நீண்ட கால பார்வை",
    share: "பகிரவும்",
    privacyPolicy: "தனியுரிமைக் கொள்கை",
    login: "உள்நுழைய",
    signup: "பதிவு செய்க",
    email: "மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    forgotPassword: "கடவுச்சொல்லை மறந்தீர்களா?",
    dontHaveAccount: "கணக்கு இல்லையா?",
    alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    continueWithGoogle: "Google உடன் தொடரவும்",
    logout: "வெளியேறு",
    welcomeBack: "மீண்டும் வருக",
    createAccount: "கணக்கை உருவாக்கவும்",
    numerology: "எண் கணிதம்",
    comingSoon: "விரைவில் வருகிறது"
  },
  [Language.TELUGU]: {
    welcome: "ఆస్ట్రో వేద ఏఐ",
    selectLanguage: "భాషను ఎంచుకోండి",
    continue: "కొనసాగించండి",
    home: "హోమ్",
    horoscope: "రాశి ఫలాలు",
    kundli: "జాతకం",
    compatibility: "పొంతన",
    chat: "ఏஐ చాట్",
    settings: "సెట్టింగులు",
    findRashi: "నా రాశి",
    dailyInsight: "నేటి సూచన",
    luckyColor: "అదృష్ట రంగు",
    luckyNumber: "అదృష్ట సంఖ్య",
    mood: "మూడ్",
    askAstro: "ఆస్ట్రో ఏஐ",
    birthDetails: "జనన వివరాలు",
    name: "పేరు",
    dob: "పుట్టిన తేదీ",
    tob: "పుట్టిన సమయం",
    pob: "పుట్టిన ప్రదేశం",
    generate: "ఫలితాన్ని పొందండి",
    partner: "భాగస్వామి వివరాలు",
    analyze: "విశ్లేషించండి",
    chatPlaceholder: "మీ భవిష్యత్తు గురించి అడగండి...",
    loading: "నక్షత్రాలను పరిశీలిస్తోంది...",
    loadingSubtitle: "జాతకం సిద్ధమవుతోంది... విశ్వం సమాధానం ఇస్తోంది",
    zodiac: { aries: "మేషం", taurus: "వృషభం", gemini: "మిథునం", cancer: "కర్కాటకం", leo: "సింహం", virgo: "కన్య", libra: "తుల", scorpio: "వృశ్చికం", sagittarius: "ధనుస్సు", capricorn: "మకరం", aquarius: "కుంభం", pisces: "మీనం" },
    settingsTitle: "సెట్టింగులు",
    notifications: "నోటిఫికేషన్లు",
    enableAlerts: "రోజువారీ రాశిఫలాలు",
    selectSign: "మీ రాశి",
    saveChanges: "సేవ్ చేయండి",
    viewDetails: "వివరాలు",
    timeframes: { today: "ఈ రోజు", tomorrow: "రేపు", weekly: "వారపు" },
    features: { zodiacSigns: "రాశులు", kundliDesc: "వేద చార్ట్", matchDesc: "ప్రేమ పొంతన" },
    profile: "ప్రొఫైల్",
    bio: "బయో",
    editProfile: "ప్రొఫైల్ సవరించు",
    cancel: "రద్దు చేయండి",
    matchTitle: "పొంతన పరిశీలన",
    matchSubtitle: "మీ ఇద్దరి మధ్య అనుకూలత",
    yourDetails: "మీ వివరాలు",
    partnerDetails: "భాగస్వామి వివరాలు",
    gender: "లింగం",
    male: "పురుషుడు",
    female: "స్త్రీ",
    other: "ఇతర",
    relType: "సంబంధ రకం",
    relTypes: { love: "ప్రేమ", marriage: "వివాహం", friendship: "స్నేహం", general: "సాధారణ" },
    checkMatch: "పొంతన చూడండి",
    matchScore: "పొంతన స్కోరు",
    strengths: "బలాలు",
    challenges: "సవాళ్లు",
    advice: "సలహా",
    emotional: "భావోద్వేగ",
    communication: "కమ్యూనికేషన్",
    longTerm: "దీర్ఘకాలిక",
    share: "షేర్ చేయండి",
    privacyPolicy: "గోప్యతా విధానం",
    login: "లాగిన్",
    signup: "సైన్ అప్",
    email: "ఇమెయిల్",
    password: "పాస్వర్డ్",
    forgotPassword: "పాస్వర్డ్ మర్చిపోయారా?",
    dontHaveAccount: "ఖాతా లేదా?",
    alreadyHaveAccount: "ఇప్పటికే ఖాతా ఉందా?",
    continueWithGoogle: "Googleతో కొనసాగండి",
    logout: "లాగ్ అవుట్",
    welcomeBack: "తిరిగి స్వాగతం",
    createAccount: "ఖాతా సృష్టించండి",
    numerology: "సంఖ్యాశాస్త్రం",
    comingSoon: "త్వరలో వస్తుంది"
  },
  [Language.GUJARATI]: {
    welcome: "એસ્ટ્રો વેદ એઆઈ",
    selectLanguage: "ભાષા પસંદ કરો",
    continue: "ચાલુ રાખો",
    home: "હોમ",
    horoscope: "રાશિફળ",
    kundli: "કુંડળી",
    compatibility: "મેળાપક",
    chat: "ચેટ",
    settings: "સેટિંગ્સ",
    findRashi: "રાશિ શોધો",
    dailyInsight: "દૈનિક સૂઝ",
    luckyColor: "શુભ રંગ",
    luckyNumber: "શુભ અંક",
    mood: "મૂડ",
    askAstro: "એસ્ટ્રો એઆઈ",
    birthDetails: "જન્મ વિગતો",
    name: "નામ",
    dob: "જન્મ તારીખ",
    tob: "જન્મ સમય",
    pob: "જન્મ સ્થળ",
    generate: "કુંડળી બનાવો",
    partner: "સાથીની વિગતો",
    analyze: "વિશ્લેષણ",
    chatPlaceholder: "તમારા ભાગ્ય વિશે પૂછો...",
    loading: "તારાઓની સલાહ...",
    loadingSubtitle: "કુંડળી તૈયાર થઈ રહી છે... બ્રહ્માંડ ગણતરી કરી રહ્યું છે",
    zodiac: { aries: "મેષ", taurus: "વૃષભ", gemini: "મિથુન", cancer: "કર્ક", leo: "સિંહ", virgo: "કન્યા", libra: "તુલા", scorpio: "વૃશ્ચિક", sagittarius: "ધનુ", capricorn: "મકર", aquarius: "કુંભ", pisces: "મીન" },
    settingsTitle: "સેટિંગ્સ",
    notifications: "સૂચનાઓ",
    enableAlerts: "દૈનિક જન્માક્ષર",
    selectSign: "તમારી રાશિ",
    saveChanges: "સાચવો",
    viewDetails: "વિગતો",
    timeframes: { today: "આજે", tomorrow: "આવતીકાલે", weekly: "સાપ્તાહિક" },
    features: { zodiacSigns: "રાશિ ચિહ્નો", kundliDesc: "વૈદિક ચાર્ટ", matchDesc: "પ્રેમ મેચ" },
    profile: "પ્રોફાઇલ",
    bio: "પરિચય",
    editProfile: "પ્રોફાઇલ સંપાદિત કરો",
    cancel: "રદ કરો",
    matchTitle: "રાશિ મેળાપક",
    matchSubtitle: "તમે બંને કેટલા સુસંગત છો",
    yourDetails: "તમારી વિગતો",
    partnerDetails: "સાથીની વિગતો",
    gender: "લિંગ",
    male: "પુરુષ",
    female: "સ્ત્રી",
    other: "અન્ય",
    relType: "સંબંધનો પ્રકાર",
    relTypes: { love: "પ્રેમ", marriage: "લગ્ન", friendship: "મિત્રતા", general: "સામાન્ય" },
    checkMatch: "મેળાપક તપાસો",
    matchScore: "સ્કોર",
    strengths: "શક્તિઓ",
    challenges: "પડકારો",
    advice: "સલાહ",
    emotional: "ભાવનાત્મક",
    communication: "વાતચીત",
    longTerm: "લાંબા ગાળાની",
    share: "શેર કરો",
    privacyPolicy: "ગોપનીયતા નીતિ",
    login: "લોગિન",
    signup: "સાઇન અપ",
    email: "ઇમેઇલ",
    password: "પાસવર્ડ",
    forgotPassword: "પાસવર્ડ ભૂલી ગયા છો?",
    dontHaveAccount: "ખાતું નથી?",
    alreadyHaveAccount: "પહેલેથી જ ખાતું છે?",
    continueWithGoogle: "Google સાથે ચાલુ રાખો",
    logout: "લૉગ આઉટ",
    welcomeBack: "ફરી સ્વાગત છે",
    createAccount: "ખાતું બનાવો",
    numerology: "અંકશાસ્ત્ર",
    comingSoon: "ટૂંક સમયમાં આવી રહ્યું છે"
  },
  [Language.KANNADA]: {
    welcome: "ಆಸ್ಟ್ರೋ ವೇದ ಎಐ",
    selectLanguage: "ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ",
    continue: "ಮುಂದುವರಿಸಿ",
    home: "ಮುಖಪುಟ",
    horoscope: "ರಾಶಿಭವಿಷ್ಯ",
    kundli: "ಜಾತಕ",
    compatibility: "ಹೊಂದಾಣಿಕೆ",
    chat: "ಚಾಟ್",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    findRashi: "ರಾಶಿ ಹುಡುಕಿ",
    dailyInsight: "ದೈನಂದಿನ ಮಾಹಿತಿ",
    luckyColor: "ಅದೃಷ್ಟ ಬಣ್ಣ",
    luckyNumber: "ಅದೃಷ್ಟ ಸಂಖ್ಯೆ",
    mood: "ಮನಸ್ಥಿತಿ",
    askAstro: "ಆಸ್ಟ್ರೋ ಎಐ",
    birthDetails: "ಜನನ ವಿವರಗಳು",
    name: "ಹೆಸರು",
    dob: "ಹುಟ್ಟಿದ ದಿನಾಂಕ",
    tob: "ಹುಟ್ಟಿದ ಸಮಯ",
    pob: "ಹುಟ್ಟಿದ ಸ್ಥಳ",
    generate: "ರಚಿಸಿ",
    partner: "ಜೊತೆಗಾರನ ವಿವರ",
    analyze: "ವಿಶ್ಲೇಷಿಸಿ",
    chatPlaceholder: "ಭವಿಷ್ಯದ ಬಗ್ಗೆ ಕೇಳಿ...",
    loading: "ನಕ್ಷತ್ರಗಳನ್ನು ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ...",
    loadingSubtitle: "ಜಾತಕ ಸಿದ್ಧವಾಗುತ್ತಿದೆ... ಬ್ರಹ್ಮಾಂಡವು ವಿವರಗಳನ್ನು ಜೋಡಿಸುತ್ತಿದೆ",
    zodiac: { aries: "ಮೇಷ", taurus: "ವೃಷಭ", gemini: "ಮಿಥುನ", cancer: "ಕರ್ಕಾಟಕ", leo: "ಸಿಂಹ", virgo: "ಕನ್ಯಾ", libra: "ತುಲಾ", scorpio: "ವೃಶ್ಚಿಕ", sagittarius: "ಧನು", capricorn: "ಮಕರ", aquarius: "ಕುಂಭ", pisces: "ಮೀನ" },
    settingsTitle: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    notifications: "ಅಧಿಸೂಚನೆಗಳು",
    enableAlerts: "ದೈನಂದಿನ ಎಚ್ಚರಿಕೆಗಳು",
    selectSign: "ನಿಮ್ಮ ರಾಶಿ",
    saveChanges: "ಉಳಿಸಿ",
    viewDetails: "ವಿವರಗಳು",
    timeframes: { today: "ಇಂದು", tomorrow: "ನಾಳೆ", weekly: "ವಾರದ" },
    features: { zodiacSigns: "ರಾಶಿ ಚಿಹ್ನೆಗಳು", kundliDesc: "ವೈದಿಕ ಚಾರ್ಟ್", matchDesc: "ಪ್ರೀತಿಯ ಹೊಂದಾಣಿಕೆ" },
    profile: "ಪ್ರೊಫೈಲ್",
    bio: "ಪರಿಚಯ",
    editProfile: "ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ",
    cancel: "ರದ್ದುಮಾಡಿ",
    matchTitle: "ಹೊಂದಾಣಿಕೆ",
    matchSubtitle: "ನೀವಿಬ್ಬರೂ ಎಷ್ಟು ಹೊಂದಿಕೆಯಾಗುತ್ತೀರಿ",
    yourDetails: "ನಿಮ್ಮ ವಿವರಗಳು",
    partnerDetails: "ಜೊತೆಗಾರನ ವಿವರಗಳು",
    gender: "ಲಿಂಗ",
    male: "ಪುರುಷ",
    female: "ಸ್ತ್ರೀ",
    other: "ಇತರೆ",
    relType: "ಸಂಬಂಧದ ಪ್ರಕಾರ",
    relTypes: { love: "ಪ್ರೀತಿ", marriage: "ವಿವಾಹ", friendship: "ಸ್ನೇಹ", general: "ಸಾಮಾನ್ಯ" },
    checkMatch: "ಹೊಂದಾಣಿಕೆ ನೋಡಿ",
    matchScore: "ಸ್ಕೋರ್",
    strengths: "ಬಲಗಳು",
    challenges: "ಸವಾಲುಗಳು",
    advice: "ಸಲಹೆ",
    emotional: "ಭಾವನಾತ್ಮಕ",
    communication: "ಸಂವಹನ",
    longTerm: "ದೀರ್ಘಕಾಲೀನ",
    share: "ಹಂಚಿಕೊಳ್ಳಿ",
    privacyPolicy: "ಗೌಪ್ಯತೆ ನೀತಿ",
    login: "ಲಾಗಿನ್",
    signup: "ಸೈನ್ ಅಪ್",
    email: "ಇಮೇಲ್",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    forgotPassword: "ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?",
    dontHaveAccount: "ಖಾತೆ ಇಲ್ಲವೇ?",
    alreadyHaveAccount: "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?",
    continueWithGoogle: "Google ನೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ",
    logout: "ಲಾಗ್ ಔಟ್",
    welcomeBack: "ಮತ್ತೆ ಸ್ವಾಗತ",
    createAccount: "ಖಾತೆ ರಚಿಸಿ",
    numerology: "ಸಂಖ್ಯಾಶಾಸ್ತ್ರ",
    comingSoon: "ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ"
  },
  [Language.MALAYALAM]: {
    welcome: "ആസ്ട്രോ വേദ എഐ",
    selectLanguage: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    continue: "തുടരുക",
    home: "ഹോം",
    horoscope: "രാശിഫലം",
    kundli: "ജാതകം",
    compatibility: "പൊരുത്തം",
    chat: "ചാറ്റ്",
    settings: "ക്രമീകരണങ്ങൾ",
    findRashi: "രാശി കണ്ടെത്തുക",
    dailyInsight: "ദിവസഫലം",
    luckyColor: "ഭാഗ്യ നിറം",
    luckyNumber: "ഭാഗ്യ സംഖ്യ",
    mood: "മൂഡ്",
    askAstro: "ആസ്ട്രോ എഐ",
    birthDetails: "ജനന വിവരങ്ങൾ",
    name: "പേര്",
    dob: "ജനന തീയതി",
    tob: "ജനന സമയം",
    pob: "ജനന സ്ഥലം",
    generate: "ഫലം",
    partner: "പങ്കാളി",
    analyze: "വിശകലനം",
    chatPlaceholder: "ഭാവിയെക്കുറിച്ച് ചോദിക്കൂ...",
    loading: "നക്ഷത്രങ്ങളെ നോക്കുന്നു...",
    loadingSubtitle: "ജാതകം തയ്യാറാകുന്നു... പ്രപഞ്ചം വിവരങ്ങൾ ശേഖരിക്കുന്നു",
    zodiac: { aries: "മേടം", taurus: "ഇടവം", gemini: "മിഥുനം", cancer: "കർക്കിടകം", leo: "ചിങ്ങം", virgo: "കന്നി", libra: "തുലാം", scorpio: "വൃശ്ചികം", sagittarius: "ധനു", capricorn: "മകരം", aquarius: "കുംഭം", pisces: "മീനം" },
    settingsTitle: "ക്രമീകരണങ്ങൾ",
    notifications: "അറിയിപ്പുകൾ",
    enableAlerts: "ദിവസേനയുള്ള അറിയിപ്പുകൾ",
    selectSign: "നിങ്ങളുടെ രാശി",
    saveChanges: "സേവ്",
    viewDetails: "വിശദാംശങ്ങൾ",
    timeframes: { today: "ഇന്ന്", tomorrow: "നാളെ", weekly: "പ്രതിവാര" },
    features: { zodiacSigns: "രാശിചിഹ്നങ്ങൾ", kundliDesc: "വേദ ജാതകം", matchDesc: "വിവാഹ പൊരുത്തം" },
    profile: "പ്രൊഫൈൽ",
    bio: "വിവരണം",
    editProfile: "പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യുക",
    cancel: "റദ്ദാക്കുക",
    matchTitle: "പൊരുത്തം പരിശോധന",
    matchSubtitle: "നിങ്ങൾ എത്രത്തോളം യോജിക്കുന്നു",
    yourDetails: "നിങ്ങളുടെ വിവരങ്ങൾ",
    partnerDetails: "പങ്കാളിയുടെ വിവരങ്ങൾ",
    gender: "ലിംഗഭേദം",
    male: "പുരുഷൻ",
    female: "സ്ത്രീ",
    other: "മറ്റുള്ളവ",
    relType: "ബന്ധം",
    relTypes: { love: "പ്രേമം", marriage: "വിവാഹം", friendship: "സൗഹൃദം", general: "പൊതുവായ" },
    checkMatch: "പരിശോധിക്കുക",
    matchScore: "സ്കോർ",
    strengths: "ശക്തികൾ",
    challenges: "വെല്ലുവിളികൾ",
    advice: "ഉപദേശം",
    emotional: "വൈകാരികം",
    communication: "ആശയവിനിമയം",
    longTerm: "ദീർഘകാല",
    share: "പങ്കിടുക",
    privacyPolicy: "സ്വകാര്യതാ നയം",
    login: "ലോഗിൻ",
    signup: "സൈൻ അപ്പ്",
    email: "ഇമെയിൽ",
    password: "പാസ്‌വേഡ്",
    forgotPassword: "പാസ്‌വേഡ് മറന്നോ?",
    dontHaveAccount: "അക്കൗണ്ട് ഇല്ലേ?",
    alreadyHaveAccount: "അക്കൗണ്ട് ഉണ്ടോ?",
    continueWithGoogle: "Google-ൽ തുടരുക",
    logout: "ലോഗ് ഔട്ട്",
    welcomeBack: "വീണ്ടും സ്വാഗതം",
    createAccount: "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
    numerology: "സംഖ്യാശാസ്ത്രം",
    comingSoon: "ഉടൻ വരുന്നു"
  },
  [Language.BENGALI]: {
    welcome: "অ্যাস্ট্রো বেদ এআই",
    selectLanguage: "ভাষা নির্বাচন",
    continue: "চালিয়ে যান",
    home: "হোম",
    horoscope: "রাশিফল",
    kundli: "কুষ্ঠি",
    compatibility: "মিল",
    chat: "চ্যাট",
    settings: "সেটিংস",
    findRashi: "রাশি খুঁজুন",
    dailyInsight: "দৈনিক অন্তর্দৃষ্টি",
    luckyColor: "শুভ রঙ",
    luckyNumber: "শুভ সংখ্যা",
    mood: "মেজাজ",
    askAstro: "অ্যাস্ট্রো এআই",
    birthDetails: "জন্ম বিবরণ",
    name: "নাম",
    dob: "জন্ম তারিখ",
    tob: "জন্ম সময়",
    pob: "জন্ম স্থান",
    generate: "তৈরি করুন",
    partner: "সঙ্গীর বিবরণ",
    analyze: "বিশ্লেষণ",
    chatPlaceholder: "ভাগ্য সম্পর্কে জিজ্ঞাসা করুন...",
    loading: "নক্ষত্রের পরামর্শ...",
    loadingSubtitle: "আপনার কুষ্ঠি তৈরি হচ্ছে... মহাবিশ্ব উত্তর সাজাচ্ছে",
    zodiac: { aries: "মেষ", taurus: "বৃষ", gemini: "মিথুন", cancer: "কর্কট", leo: "সিংহ", virgo: "কন্যা", libra: "তুলা", scorpio: "বৃশ্চিক", sagittarius: "ধনু", capricorn: "মকর", aquarius: "কুম্ভ", pisces: "মীন" },
    settingsTitle: "সেটিংস",
    notifications: "বিজ্ঞপ্তি",
    enableAlerts: "দৈনিক রাশিফল",
    selectSign: "আপনার রাশি",
    saveChanges: "সংরক্ষণ",
    viewDetails: "বিস্তারিত",
    timeframes: { today: "আজ", tomorrow: "আগামীকাল", weekly: "সাপ্তাহিক" },
    features: { zodiacSigns: "রাশি চক্র", kundliDesc: "বৈদিক কুষ্ঠি", matchDesc: "প্রেমের মিল" },
    profile: "প্রোফাইল",
    bio: "বায়ো",
    editProfile: "প্রোফাইল এডিট করুন",
    cancel: "বাতিল",
    matchTitle: "রাশি মিল",
    matchSubtitle: "আপনারা দুজন কতটা মানানসই",
    yourDetails: "আপনার বিবরণ",
    partnerDetails: "সঙ্গীর বিবরণ",
    gender: "লিঙ্গ",
    male: "পুরুষ",
    female: "মহিলা",
    other: "অন্যান্য",
    relType: "সম্পর্কের ধরন",
    relTypes: { love: "প্রেম", marriage: "বিবাহ", friendship: "বন্ধুত্ব", general: "সাধারণ" },
    checkMatch: "মিল দেখুন",
    matchScore: "স্কোর",
    strengths: "শক্তি",
    challenges: "চ্যালেঞ্জ",
    advice: "পরামর্শ",
    emotional: "আবেগপূর্ণ",
    communication: "যোগাযোগ",
    longTerm: "দীর্ঘমেয়াদী",
    share: "শেয়ার করুন",
    privacyPolicy: "গোপনীয়তা নীতি",
    login: "লগইন",
    signup: "সাইন আপ",
    email: "ইমেল",
    password: "পাসওয়ার্ড",
    forgotPassword: "পাসওয়ার্ড ভুলে গেছেন?",
    dontHaveAccount: "অ্যাকাউন্ট নেই?",
    alreadyHaveAccount: "ইতিমধ্যে অ্যাকাউন্ট আছে?",
    continueWithGoogle: "Google এর সাথে চালিয়ে যান",
    logout: "লগ আউট",
    welcomeBack: "ফিরে আসায় স্বাগতম",
    createAccount: "অ্যাকাউন্ট তৈরি করুন",
    numerology: "সংখ্যাতত্ত্ব",
    comingSoon: "শীঘ্রই আসছে"
  },
  [Language.PUNJABI]: {
    welcome: "ਐਸਟ੍ਰੋ ਵੇਦ ਏਆਈ",
    selectLanguage: "ਭਾਸ਼ਾ ਚੁਣੋ",
    continue: "ਜਾਰੀ ਰੱਖੋ",
    home: "ਘਰ",
    horoscope: "ਰਾਸ਼ੀਫਲ",
    kundli: "ਕੁੰਡਲੀ",
    compatibility: "ਮੈਚ",
    chat: "ਗੱਲਬਾਤ",
    settings: "ਸੈਟਿੰਗਾਂ",
    findRashi: "ਰਾਸ਼ੀ ਲੱਭੋ",
    dailyInsight: "ਰੋਜ਼ਾਨਾ",
    luckyColor: "ਸ਼ੁਭ ਰੰਗ",
    luckyNumber: "ਸ਼ੁਭ ਅੰਕ",
    mood: "ਮੂਡ",
    askAstro: "ਐਸਟ੍ਰੋ ਏਆਈ",
    birthDetails: "ਜਨਮ ਵੇਰਵੇ",
    name: "ਨਾਮ",
    dob: "ਜਨਮ ਮਿਤੀ",
    tob: "ਜਨਮ ਸਮਾਂ",
    pob: "ਜਨਮ ਸਥਾਨ",
    generate: "ਜਾਣੋ",
    partner: "ਸਾਥੀ",
    analyze: "ਵਿਸ਼ਲੇਸ਼ਣ",
    chatPlaceholder: "ਕਿਸਮਤ ਬਾਰੇ ਪੁੱਛੋ...",
    loading: "ਤਾਰਿਆਂ ਨਾਲ...",
    loadingSubtitle: "ਤੁਹਾਡੀ ਕੁੰਡਲੀ ਤਿਆਰ ਹੋ ਰਹੀ ਹੈ... ਬ੍ਰਹਿਮੰਡ ਵੇਰਵੇ ਜੋੜ ਰਿਹਾ ਹੈ",
    zodiac: { aries: "ਮੇਸ਼", taurus: "ਵ੍ਰਿਸ਼", gemini: "ਮਿਥੁਨ", cancer: "ਕਰਕ", leo: "ਸਿੰਘ", virgo: "ਕੰਨਿਆ", libra: "ਤੁਲਾ", scorpio: "ਵ੍ਰਿਸ਼ਚਿਕ", sagittarius: "ਧਨੁ", capricorn: "ਮਕਰ", aquarius: "ਕੁੰਭ", pisces: "ਮੀਨ" },
    settingsTitle: "ਸੈਟਿੰਗਾਂ",
    notifications: "ਸੂਚਨਾਵਾਂ",
    enableAlerts: "ਰੋਜ਼ਾਨਾ ਚੇਤਾਵਨੀਆਂ",
    selectSign: "ਆਪਣੀ ਰਾਸ਼ੀ",
    saveChanges: "ਸੰਭਾਲੋ",
    viewDetails: "ਵੇਰਵੇ",
    timeframes: { today: "ਅੱਜ", tomorrow: "ਕੱਲ੍ਹ", weekly: "ਹਫਤਾਵਾਰੀ" },
    features: { zodiacSigns: "ਰਾਸ਼ੀ ਚਿੰਨ੍ਹ", kundliDesc: "ਵੈਦਿਕ ਚਾਰਟ", matchDesc: "ਪਿਆਰ ਮੈਚ" },
    profile: "ਪ੍ਰੋਫਾਈਲ",
    bio: "ਬਾਇਓ",
    editProfile: "ਪ੍ਰੋਫਾਈਲ ਸੋਧੋ",
    cancel: "ਰੱਦ ਕਰੋ",
    matchTitle: "ਮੈਚ ਅਨੁਕੂਲਤਾ",
    matchSubtitle: "ਪਤਾ ਕਰੋ ਕਿ ਤੁਸੀਂ ਦੋਵੇਂ ਕਿੰਨੇ ਵਧੀਆ ਹੋ",
    yourDetails: "ਤੁਹਾਡੇ ਵੇਰਵੇ",
    partnerDetails: "ਸਾਥੀ ਦੇ ਵੇਰਵੇ",
    gender: "ਲਿੰਗ",
    male: "ਪੁਰਸ਼",
    female: "ਔਰਤ",
    other: "ਹੋਰ",
    relType: "ਰਿਸ਼ਤੇ ਦੀ ਕਿਸਮ",
    relTypes: { love: "ਪਿਆਰ", marriage: "ਵਿਆਹ", friendship: "ਦੋਸਤੀ", general: "ਆਮ" },
    checkMatch: "ਮੈਚ ਚੈੱਕ ਕਰੋ",
    matchScore: "ਸਕੋਰ",
    strengths: "ਤਾਕਤ",
    challenges: "ਚੁਣੌਤੀਆਂ",
    advice: "ਸਲਾਹ",
    emotional: "ਭਾਵਨਾਤਮਕ",
    communication: "ਗੱਲਬਾਤ",
    longTerm: "ਲੰਬੇ ਸਮੇਂ ਲਈ",
    share: "ਸਾਂਝਾ ਕਰੋ",
    privacyPolicy: "ਪਰਦੇਦਾਰੀ ਨੀਤੀ",
    login: "ਲੌਗਇਨ",
    signup: "ਸਾਈਨ ਅਪ",
    email: "ਈਮੇਲ",
    password: "ਪਾਸਵਰਡ",
    forgotPassword: "ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?",
    dontHaveAccount: "ਖਾਤਾ ਨਹੀਂ ਹੈ?",
    alreadyHaveAccount: "ਪਹਿਲਾਂ ਹੀ ਖਾਤਾ ਹੈ?",
    continueWithGoogle: "Google ਨਾਲ ਜਾਰੀ ਰੱਖੋ",
    logout: "ਲੌਗ ਆਉਟ",
    welcomeBack: "ਵਾਪਸੀ ਤੇ ਜੀ ਆਇਆਂ ਨੂੰ",
    createAccount: "ਖਾਤਾ ਬਣਾਓ",
    numerology: "ਅੰਕ ਵਿਗਿਆਨ",
    comingSoon: "ਜਲਦੀ ਆ ਰਿਹਾ ਹੈ"
  },
  [Language.ODIA]: {
    welcome: "ଆଷ୍ଟ୍ରୋ ବେଦ ଏଆଇ",
    selectLanguage: "ଭାଷା ବାଛନ୍ତୁ",
    continue: "ଆଗକୁ ବଢନ୍ତୁ",
    home: "ମୂଳପୃଷ୍ଠା",
    horoscope: "ରାଶିଫଳ",
    kundli: "କୁଣ୍ଡଳୀ",
    compatibility: "ମେଳକ",
    chat: "ଚାଟ୍",
    settings: "ସେଟିଂସ",
    findRashi: "ରାଶି ଖୋଜନ୍ତୁ",
    dailyInsight: "ଦୈନିକ",
    luckyColor: "ଶୁଭ ରଙ୍ଗ",
    luckyNumber: "ଶୁଭ ସଂଖ୍ୟା",
    mood: "ମନୋଭାବ",
    askAstro: "ଆଷ୍ଟ୍ରୋ ଏଆଇ",
    birthDetails: "ଜନ୍ମ ବିବରଣୀ",
    name: "ନାମ",
    dob: "ଜନ୍ମ ତାରିଖ",
    tob: "ଜନ୍ମ ସମୟ",
    pob: "ଜନ୍ମ ସ୍ଥାନ",
    generate: "ଜାଣନ୍ତୁ",
    partner: "ସାଥୀ",
    analyze: "ବିଶ୍ଲେଷଣ",
    chatPlaceholder: "ଭାଗ୍ୟ ବିଷୟରେ ପଚାରନ୍ତୁ...",
    loading: "ତାରା ମାନଙ୍କ ସହ...",
    loadingSubtitle: "କୁଣ୍ଡଳୀ ପ୍ରସ୍ତୁତ ହେଉଛି... ବ୍ରହ୍ମାଣ୍ଡ ଉତ୍ତର ଖୋଜୁଛି",
    zodiac: { aries: "ମେଷ", taurus: "ବୃଷ", gemini: "ମିଥୁନ", cancer: "କର୍କଟ", leo: "ସିଂହ", virgo: "କନ୍ୟା", libra: "ତୁଳା", scorpio: "ବିଛା", sagittarius: "ଧନୁ", capricorn: "ମକର", aquarius: "କୁମ୍ଭ", pisces: "ମୀନ" },
    settingsTitle: "ସେଟିଂସ",
    notifications: "ବିଜ୍ଞପ୍ତି",
    enableAlerts: "ଦୈନିକ ରାଶିଫଳ",
    selectSign: "ଆପଣଙ୍କ ରାଶି",
    saveChanges: "ସେଭ୍ କରନ୍ତୁ",
    viewDetails: "ବିବରଣୀ",
    timeframes: { today: "ଆଜି", tomorrow: "ଆସନ୍ତାକାଲି", weekly: "ସାପ୍ତାହିକ" },
    features: { zodiacSigns: "ରାଶି ଚିହ୍ନ", kundliDesc: "ବୈଦିକ ଚାର୍ଟ", matchDesc: "ପ୍ରେମ ମେଳକ" },
    profile: "ପ୍ରୋଫାଇଲ୍",
    bio: "ବାୟୋ",
    editProfile: "ପ୍ରୋଫାଇଲ୍ ଏଡିଟ୍",
    cancel: "ବାତିଲ୍",
    matchTitle: "ରାଶି ମେଳକ",
    matchSubtitle: "ଆପଣ ଦୁହେଁ କେତେ ମିଶୁଛନ୍ତି",
    yourDetails: "ଆପଣଙ୍କ ବିବରଣୀ",
    partnerDetails: "ସାଥୀଙ୍କ ବିବରଣୀ",
    gender: "ଲିଙ୍ଗ",
    male: "ପୁରୁଷ",
    female: "ମହିଳା",
    other: "ଅନ୍ୟ",
    relType: "ସମ୍ପର୍କ ପ୍ରକାର",
    relTypes: { love: "ପ୍ରେମ", marriage: "ବିବାହ", friendship: "ବନ୍ଧୁତା", general: "ସାଧାରଣ" },
    checkMatch: "ମେଳକ ଦେଖନ୍ତୁ",
    matchScore: "ସ୍କୋର",
    strengths: "ଶକ୍ତି",
    challenges: "ଚ୍ୟାଲେଞ୍ଜ",
    advice: "ପରାମର୍ଶ",
    emotional: "ଭାବପ୍ରବଣ",
    communication: "ଯୋଗାଯୋଗ",
    longTerm: "ଦୀର୍ଘକାଳୀନ",
    share: "ସେୟାର କରନ୍ତୁ",
    privacyPolicy: "ଗୋପନୀୟତା ନୀତି",
    login: "ଲଗ୍ ଇନ୍",
    signup: "ସାଇନ୍ ଅପ୍",
    email: "ଇମେଲ୍",
    password: "ପାସୱାର୍ଡ",
    forgotPassword: "ପାସୱାର୍ଡ ଭୁଲିଗଲେ?",
    dontHaveAccount: "ଆକାଉଣ୍ଟ ନାହିଁ?",
    alreadyHaveAccount: "ଆକାଉଣ୍ଟ ଅଛି?",
    continueWithGoogle: "Google ସହିତ ଜାରି ରଖନ୍ତୁ",
    logout: "ଲଗ୍ ଆଉଟ୍",
    welcomeBack: "ସ୍ୱାଗତ",
    createAccount: "ଆକାଉଣ୍ଟ ଖୋଲନ୍ତୁ",
    numerology: "ସଂଖ୍ୟା ଜ୍ୟୋତିଷ",
    comingSoon: "ଶୀଘ୍ର ଆସୁଛି"
  }
};